<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>HvZBot</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DSharpPlus" Version="4.5.0" />
    <PackageReference Include="DSharpPlus.CommandsNext" Version="4.5.0" />
    <PackageReference Include="DSharpPlus.SlashCommands" Version="4.5.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="SQLite\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="SQLite\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="SQLite\**" />
    <None Remove="secrets.env" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="WebService\" />
  </ItemGroup>

</Project>
